# -*- coding: utf-8 -*-
"""Day 3(Functions)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ixJTMZzF4Jo1Spz3sZ0muTx5Os-51ajL
"""

'''Practiced Python functions, parameters, return values, loops, and conditional statements by solving basic programming problems. Built a Health & Fitness Analyzer mini project to calculate average, highest, and lowest weight, determine BMI, classify health status, and generate a patient report using modular programming.'''

# Creating a Function
def maryam():
  print('hello maryam!')
maryam()

# Multiple Parameters
def list(pat_name,pat_age):
  print("Patient Name:", pat_name)
  print("Patient Age:", pat_age)
list("Breera", 34)

# function return value
def math(square):
  num = square * square
  print(num)
math(2)

def add(var_1,var_2):
  return var_1 + var_2
add(20,10)

# Default Parameters
def city(city_name = 'Karachi'):
  print(city_name)
city()
city('Islamabad')

# Subtract two numbers
def sub(num1,num2):
  return num1 - num2
sub(50,45)

# Area of Rectangale
def area_of_rectangle(l,w):
  return l*w
area_of_rectangle(2345,78)

# check whether number even or odd
def func(num):
  if num%2==0:
    print('Number is Even!')
  else:
    print('Number is Odd!')
func(int(input("Enter a Number: ")))

# Find 3 Maximum Number
def maximum(a,b,c,d,e):
  return max(a,b,c,d,e)
maximum(34,987,90,23,54)

# mini project (FITNESS ANALYZER)
def patient_detail():
  print ("----Patient Details-----")
  user = input(str("Patient Name: "))
  pt_height = float(input("Patient Height in (meters): "))
  pt_age = int(input("Patient Age: "))
  pt_gender = input(str("Patient Gender (F & M): "))

  return user,pt_height,pt_age,pt_gender

def input_weight():
  total = 0
  highest_weight = 0
  lowest_weight = 0

  weight_readings = int(input("Enter Number of Weight Readings: "))

  for i in range(weight_readings):
    weight = float(input("Enter Weight: "))
    total += weight

    if i == 0:
      highest_weight = weight
      lowest_weight = weight
    else:
      if weight > highest_weight:
        highest_weight = weight
      if weight < lowest_weight:
        lowest_weight = weight

  average = total/weight_readings

  return average,highest_weight,lowest_weight

def bmi(weight,height):
  return weight / (height * height)

def bmi_category(bmi):
  if bmi < 18.5:
    return "Underweight"
  elif bmi < 25:
    return "Normal Weight"
  elif bmi < 30:
    return "Overweight"
  else:
    return "Obese"

def main():
  user,pt_height,pt_age,pt_gender = patient_detail()
  average,highest_weight,lowest_weight = input_weight()
  bmi_value = bmi(average,pt_height)
  category = bmi_category(bmi_value)

  print('--------REPORT---------')
  print('Patient Name:',user)
  print('Patient Age:',pt_age)
  print('Patient Gender:',pt_gender)
  print('Patient Height:',pt_height)
  print('Average Weight:',average)
  print('Highest Weight:',highest_weight)
  print('Lowest Weight:',lowest_weight)
  print('BMI Value:',bmi_value)
  print('BMI Category:',category)

main()

