# -*- coding: utf-8 -*-
"""Day 01(Python Basics)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NiBP63DWBt6KGWTjLrzms4ULkdMgM6kR
"""

'''On Day 1 of my Python learning journey, I learned the fundamentals of Python programming, including variables, data types, user input, arithmetic operations, conditional statements, and formatted output.

To apply these concepts, I built a Student Short Transcript Generator. The program collects student information, subject names, and marks, then calculates the total marks, average, percentage, grade, 6th semester GPA, and overall CGPA using credit-hour weighting. This project helped me understand how basic Python concepts can be combined to solve a real-world academic problem.'''

#How to print any statement?
print("Hi, I am Maryam Riaz")

#Comments in two ways by using hastages or using'''

#Variables
name = 'maryam'
cgpa = 3.86
print(name)
print(cgpa)

#Data Type
customer_name = 'Sana Afridi'
customer_age = 34
product_purchase = True
price_of_product = 67.23
no_cust = None
print(type(customer_name))
print(type(customer_age))
print(type(product_purchase))
print(type(price_of_product))
print(type(no_cust))

# Taking Input
name = input(str('Enter Name of Emp: '))
age = int(input('Enter Age of Emp: '))
sal = eval(input('Enter Salary of Emp: '))

#Building Student Info Card
print('~~~~~~~~~~~~~~STUDENT CARD~~~~~~~~~~~~~~')
name = input(str('Name: '))
age = int(input('Age: '))
uni = input(str('University: '))
cgpa = float(input('CGPA: '))

#Short Transcript of 6TH SEMESTER

#Student Info
name = input(str('name: '))
semester = int(input('Enter semester: '))
uni_name = input(str('University Name: '))


#Semester Details

#Course Details
sub_1 = input(str('SUB 1:'))
marks_sub_1 = float(input('Marks of sub 1: '))
sub_2 = input(str('SUB 2:'))
marks_sub_2 = float(input('Marks of sub 2: '))
sub_3 = input(str('SUB 3:'))
marks_sub_3 = float(input('Marks of sub 3: '))
sub_4 = input(str('SUB 4:'))
marks_sub_4 = float(input('Marks of sub 4: '))
sub_5 = input(str('SUB 5:'))
marks_sub_5 = float(input('Marks of sub 5: '))

total = marks_sub_1 + marks_sub_2 + marks_sub_3 + marks_sub_4 +marks_sub_5
average = total/5
per = (total/500)*100

#GPA
if per >= 90:
  cur_gpa = 4.00
elif per >=85 and per <90:
  cur_gpa = 3.67
elif per >=80 and per <85:
  cur_gpa = 3.33
elif per >=75 and per <80:
  cur_gpa = 3.00
elif per >=70 and per <75:
  cur_gpa = 2.67
elif per >=65 and per <70:
  cur_gpa = 2.33
elif per >=60 and per <65:
  cur_gpa = 2.00
else:
  cur_gpa = 0.00

s1_gpa = float(input('GPA_SES1: '))
CH_S1 = int(input('Credit Hours_SES1: '))
s2_gpa = float(input('GPA_SES2: '))
CH_S2 = int(input('Credit Hours_SES2: '))
s3_gpa = float(input('GPA_SES3: '))
CH_S3 = int(input('Credit Hours_SES3: '))
s4_gpa = float(input('GPA_SES4: '))
CH_S4 = int(input('Credit Hours_SES4: '))
s5_gpa = float(input('GPA_SES5: '))
CH_S5 = int(input('Credit Hours_SES5: '))
s6_gpa = cur_gpa
CH_S6 = int(input('Credit Hours_SES6: '))

total_GPA_point = s1_gpa*CH_S1 + s2_gpa*CH_S2 + s3_gpa*CH_S3 + s4_gpa*CH_S4 + s5_gpa*CH_S5 + s6_gpa*CH_S6

total_credit_hours = CH_S1 + CH_S2 + CH_S3 + CH_S4 + CH_S5 + CH_S6

cgpa = total_GPA_point/total_credit_hours


print('~~~~~~~~~~~~~~SHORT TRANSCRIPT~~~~~~~~~~~~~~')

print('~~~~~~~~~~~~~~STUDENT DETAILS~~~~~~~~~~~~~~~')
print('Student Name: ', name)
print('University Name: ',uni_name)
print ('Current Semester Transcript: ', semester)

print('~~~~~~~~~~~~~~MARKS SHEET~~~~~~~~~~~~~~')
print(sub_1, marks_sub_1)
print(sub_2, marks_sub_2)
print(sub_3, marks_sub_3)
print(sub_4, marks_sub_4)
print(sub_5,marks_sub_5)


print('Total Obtained Marks: ', total)
print('Average Marks: ', average)
print('Percentage: ', per, '%')

#Grading
if per >= 90:
  print('Grade A: Outstanding!')
elif per >=80:
  print('Grade A- : Excellent!')
elif per >=70:
  print('Grade B: Good!')
elif per >=55:
  print('Grade B- : Fair!')
else:
  print('Grade F: Worked Hard!')

#GPA
print('6th Semester GPA: ', cur_gpa)

#CGPA
print('CGPA: ',cgpa)

print('~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~')