# -*- coding: utf-8 -*-
"""Day 2(Loops)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lDecLYzsmT8IYF14HpI94ddxaTgFeW5w
"""

'''Practiced Python loops (for and while), range(), break, and continue by solving beginner programming problems. Built two mini projects—Sales Analyzer and Temperature Analyzer—to apply loops, conditional statements, and basic data analysis concepts.'''

for i in range (1,10):
  print(i)

i = 0
while i < 10:
  i = i + 1
  print(i)

# print a table using for loop
for i in range (1,10):
  print("2 * ",i, "=", i*2)

#print table using while loop
num = 2
i =1
while i<=10:
  print(num*i)
  i = i + 1

#print table using user input
user = int(input('Enter Table Number: '))
for i in range(1,11):
  print(i*user)

#print total sum of numbers from 1-100
sum = 0
for i in range(1,101):
  sum = sum + i
print(sum)

#print even numbers
print("Even Numbers: ")
for i in range(1,51):
  if i%2 == 0:
    print(i)

#print odd numbers
for i in range(1,31):
  if i%2 != 0:
    print(i)

#taking factorical using math lib
import math
fac = math.factorial(5)
print(fac)

#taking factorial using logic
n = int(input('Enter Number: '))
result = 1
for i in range(1, n + 1):
  if i < 0:
    print('Error')
  result = result * i
  print(result)

#countdown timer
import time
target = int(input('Enter Number: '))
count = 1
while count <= target:
  print(count)
  time.sleep(1)
  count = count + 1
print('COMPLETED!')

#Continue Statement
i = 0
while i < 10:
  i = i + 1
  if i == 6:
    continue
  print(i)

#Break Statement
for i in range(1,20):
  if i == 15:
    break
  print(i)

#skip numbers
for i in range(1,21):
  if i%3 == 0:
    continue
  print(i)

#stop a number
i=0
while i<100:
  if i == 51:
    break
  i = i + 1
  print(i)

# first 20 square numbers
i = 0
while i < 21:
  print(i*i)
  i = i + 1

# count a digit
user = int(input("Enter a number: "))
count = 0
while user > 0:
  user = user // 10
  count = count + 1
print("Total Digits: ", count)

# Reverse a number(First convert number into string then reverse)
user = int(input('Enter Number: '))
rev = "".join(reversed(str(user)))
print(rev)

# mini project
print("--------SALES ANALYZER SHORT REPORT FOR 7 DAYS-------")
user = input(str("Enter a name: "))

total_sales = 0
avg_sales = 0
top_sales =0
low_sales = 0

for day in range(1,8):
  sales = int(input("Enter Sales for Day" + str(day) + ':'))

  #total sales
  total_sales = total_sales + sales

  #Top sales
  if sales > top_sales:
    top_sales =sales

  #Lowest sales
  if sales < low_sales:
    low_sales = sales

# average sales

avgg_sales = total_sales / 7

print("Total Sales Of 7 Days: ", total_sales)
print("Average Sales Of 7 Days: ", avgg_sales)
print("Top Sales Of 7 Days: ", top_sales)
print("Lowest Sales Of 7 Days: ", low_sales)

if avgg_sales >= 5000:
  print("GOOD SALES!")
else:
  print("BAD SALES!")

# Temperature Analyzer
print("----------Temperature Analyzer-----------")

high_temp = 0
low_temp = 0
total_temp = 0
avg_temp = 0
hot_days = 0
cold_days = 0

for days in range(1,8):
  temp = float(input("Enter Temperature in Degree" + str(days) + ':'))

  #count of hot & cold days
  if temp >= 35:
    hot_days = hot_days + 1
  else:
    cold_days = cold_days + 1

#lowest and highest temperature
  if days == 1:
    high_temp = temp
    low_temp = temp
  else:
    if temp > high_temp:
      high_temp = temp
    if temp < low_temp:
      low_temp = temp

  #total temperature
  total_temp = total_temp + temp

#average temperature
avgg_temp = total_temp / 7


print("Average Temperature Of 7 Days: ", avgg_temp)
print("Highest Temperature Of 7 Days: ", high_temp)
print("Lowest Temperature Of 7 Days: ", low_temp)
print('Total Hot Days: ', hot_days)
print('Total Cold Days: ', cold_days)

if avgg_temp >= 35:
  print("Hot Weather!")
elif avgg_temp >= 25:
  print("Moderate Weather!")
else:
  print("Cold Weather!")