# -*- coding: utf-8 -*-
"""Day 04(Lists)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q09d_hy8C-6WzCOiq3LbGfOgX1q8IV0y
"""

# Creating a list
siblings = ['maryam','ali','manaal']
print(siblings)
print(type(siblings))

# Acessing a Element
cars = ['honda','cultus','alto','civic','mehran','bmw','audi']

print(cars[-2])
print(cars[1])
print(cars[0])

print(cars)

# update or replace the element
cars[4] = 'ferrari'
print(cars)

'''cars[-5] = ''
print(cars)'''

cars[-5] = 'byd'
print(cars)

# append() list
cars.append('alto')
print(cars)

# insert the element
cars.insert(-4, 'kia')
print(cars)

# remove an element using remove()
cars.remove('kia')
print(cars)

# remove an element using pop()
cars.pop(1) #By using index remove element
cars.pop() #last element remove
print(cars)

# remove an element using del
del cars[3]
print(cars)

# Find len of lists
len(cars)

# sum of list
sal = [230000,45678,980000]
sum(sal)

# max & min list
sales = [789,5673,892,8642,67,245,891,965,89]
print("Maximum Sales: ", max(sales))
print("Minimum Sales: ", min(sales))

# sorting in list

num = [67,54,2,78,56,9,90,78,23,52,89,261,82,825,85,12]
num.sort(reverse = True) # List Sorted in Descending Order
print(num)

num.sort() # Sorted in Ascending Order
print(num)

names = ['Eshal','Areeba','Yumna']
names.sort()
print(" Names print a/c to First Letter in a-z:", names)

names.sort(reverse = True)
print(" Names print a/c to First Letter in z-a:", names)

company = ['google','Devsinc','IBM','walmart','amazon']
company.sort() # arrange a/c to upper letter
print(company)

# arrange in lower letter
company.sort(key = str.lower)
print(company)

# Creating Shopping Cart

shp_cart = ['Butter','Milk','Shan Packet Masla','Spoons','Bread']

# Replace item in cart
shp_cart[4] = 'Water Bottle'
shp_cart[1] = 'Juice'

# Add an item
shp_cart.append('Cup')
shp_cart.insert(3, 'Soap')

# Removing item in cart
shp_cart.remove('Butter')
shp_cart.pop()

# Final items in cart
print(shp_cart)
print("Total Items in cart: ", len(shp_cart))

# Mini Project (Employee Salary Analyzer)

Emp_sal = []

for i in range(0,10):
  admin = int(input(f"Enter a Employee {i+1} Salary: "))
  Emp_sal.append(admin)
print("\nEmployes Salaries: ", Emp_sal)

print("\nTotal Employee Salary: ", len(Emp_sal))
print("Sum of Salary: ", sum(Emp_sal))
print("Average Salary: ", sum(Emp_sal)/len(Emp_sal))
print("Highest Salary: ", max(Emp_sal))
print("Lowest Salary: ", min(Emp_sal))

Emp_sal.pop()
print("\nRemove Salary of 10 Employee: ",Emp_sal)

Emp_sal.append(340000)
print("\nAfter Adding New Salary: ",Emp_sal)

Emp_sal.sort()
print("Salary in Ascending Order: ", Emp_sal)

Emp_sal.sort(reverse = True)
print("Salary in Descending Order: ", Emp_sal)